### ISSUE TITLE
inaccurate evaluation results with best_model checkpoint

### ISSUE THREAD

**Issue by Park-ing-lot** [HKUST-KnowComp/CAR#1]
Hi!
I evaluated the best QA model (DeBERTa-v3-Large) you provided, but the scores are slightly different from the paper's scores.
(ex. 61.2(best_model) vs. 64.0(paper) on SIQA)

I use "evaluate_all.py" code for evaluating.
What is the right way to evaluate?

**Comment by MighTy-Weaver** [comment]
Hi! Thanks for the question. I've just uploaded a new checkpoint that should yield slightly better results compared to what we reported in the paper (Average: 74.33). For evaluation, you can use the evaluate_all.py script, which should work fine. If you have access to large GPUs, say at least 48G, I recommend trying to evaluate PIQA with a longer maximum sequence length. Currently, it's set to 60.

**Comment by Park-ing-lot** [comment]
Thank you for your quick response!

I should use the new checkpoint and change the sequence length for the evaluation.
